# .github/workflows/mirror.yml
name: 'mirror'
on:
  push:
    branches:
        - gh-actions
  schedule:
   - cron: '30 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: mirror
    steps:
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v3
        with:
          origin: 'https://nv-tegra.nvidia.com/r/linux-nvgpu.git'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
